In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### Sentences 
sent = [ 'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [7]:
sent 

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
## Define the vocabulary size 
voc_size = 10000

In [9]:
### One Hot Representation 
one_hot_repr = [one_hot(words, voc_size)for words in sent]
one_hot_repr

[[7086, 3329, 8804, 5514],
 [7086, 3329, 8804, 3460],
 [7086, 9125, 8804, 6491],
 [3820, 6253, 3284, 4571, 3355],
 [3820, 6253, 3284, 4571, 5228],
 [6814, 7086, 144, 8804, 4898],
 [7550, 5615, 218, 4571]]

In [10]:
### Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen = sent_length)  #You can also use post for adding zeros after 
print(embedded_docs)

[[   0    0    0    0 7086 3329 8804 5514]
 [   0    0    0    0 7086 3329 8804 3460]
 [   0    0    0    0 7086 9125 8804 6491]
 [   0    0    0 3820 6253 3284 4571 3355]
 [   0    0    0 3820 6253 3284 4571 5228]
 [   0    0    0 6814 7086  144 8804 4898]
 [   0    0    0    0 7550 5615  218 4571]]


In [13]:
## Feature representation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 68ms/step


array([[[ 0.0069278 , -0.00511782,  0.01035545, -0.04816777,
          0.00615896,  0.02559922,  0.00569073, -0.02928116,
         -0.04324067, -0.01642475],
        [ 0.0069278 , -0.00511782,  0.01035545, -0.04816777,
          0.00615896,  0.02559922,  0.00569073, -0.02928116,
         -0.04324067, -0.01642475],
        [ 0.0069278 , -0.00511782,  0.01035545, -0.04816777,
          0.00615896,  0.02559922,  0.00569073, -0.02928116,
         -0.04324067, -0.01642475],
        [ 0.0069278 , -0.00511782,  0.01035545, -0.04816777,
          0.00615896,  0.02559922,  0.00569073, -0.02928116,
         -0.04324067, -0.01642475],
        [-0.00928131,  0.02906756, -0.00132401,  0.03712869,
          0.03117004, -0.00011847,  0.0303526 , -0.01379161,
         -0.01095513,  0.02704645],
        [ 0.02776177, -0.00390798, -0.03414539,  0.01012627,
          0.00860199, -0.01446962,  0.03709468,  0.0328103 ,
          0.03839842, -0.01867096],
        [ 0.01648675,  0.01879456,  0.02394334, -0.0

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 7086, 3329, 8804, 5514])

In [18]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 34ms/step


array([[ 0.0069278 , -0.00511782,  0.01035545, -0.04816777,  0.00615896,
         0.02559922,  0.00569073, -0.02928116, -0.04324067, -0.01642475],
       [ 0.0069278 , -0.00511782,  0.01035545, -0.04816777,  0.00615896,
         0.02559922,  0.00569073, -0.02928116, -0.04324067, -0.01642475],
       [ 0.0069278 , -0.00511782,  0.01035545, -0.04816777,  0.00615896,
         0.02559922,  0.00569073, -0.02928116, -0.04324067, -0.01642475],
       [ 0.0069278 , -0.00511782,  0.01035545, -0.04816777,  0.00615896,
         0.02559922,  0.00569073, -0.02928116, -0.04324067, -0.01642475],
       [-0.00928131,  0.02906756, -0.00132401,  0.03712869,  0.03117004,
        -0.00011847,  0.0303526 , -0.01379161, -0.01095513,  0.02704645],
       [ 0.02776177, -0.00390798, -0.03414539,  0.01012627,  0.00860199,
        -0.01446962,  0.03709468,  0.0328103 ,  0.03839842, -0.01867096],
       [ 0.01648675,  0.01879456,  0.02394334, -0.02448839,  0.00944419,
         0.01827166,  0.03718462, -0.04898655